export const categoryIcon: Record<string, string> = {
    Travel: '🚗 ',
    Exam: '📝',
    Work: '💼',
    Shopping: '🛍️',
    Hospital: '🏥',
    Meeting: '👥',
    Birthday: '🎂',
    Anniversary: '💑',
    Party: '🎉',
    Volunteer: '🤝',
    Teambuilding: '🤼',
    Training: '🏋️',
    Seminar: '📚',
    Course: '🎓',
    Conference: '🎙️',
    Webinar: '🖥️',
    Wedding: '💒',
    Engagement: '💍',
    Reception: '🍾',
    Ceremony: '🎊',
    Reunion: '👪',
    Festival: '🎪',
    Concert: '🎸',
    Show: '🎭',
    Exhibition: '🖼️',
    Fair: '🎡',
    Market: '🏪',
    'Flea Market': '🛒',
    Carnival: '🎠',
    Parade: '🎉',
    Sport: '⚽',
    Game: '🎮',
    Match: '🏆',
    Tournament: '🏅'
};